### ISSUE TITLE
피보나 치킨을 위한 js

### ISSUE THREAD

**Issue by sosoYim** [Hoya-kim/fibona-chiken#4]

**Comment by sosoYim** [comment]
댓글을 이렇게 달면 assign을 하실 수 있는건가요

**Comment by sosoYim** [comment]
@Hoya-kim ?

**Comment by Hoya-kim** [comment]
> @Hoya-kim ?

늦게봐서 죄송합니다 ㅠㅠ

- [ ] 알고리즘 찾기
- [ ] 코드 구현

이렇게 진행해주시면 되겠습니다

**Comment by Hoya-kim** [comment]
@sosoYim 

html pull request 머지되면
(fetch, merge) => pull 하시고 js 붙이시면 될 것 같습니다!

**Comment by sosoYim** [comment]
@Hoya-kim 넵! 아직 머지 안된 상태죠??

**Comment by Hoya-kim** [comment]
> @Hoya-kim 넵! 아직 머지 안된 상태죠??

@sosoYim 
html 완료되었습니다 #5 
pull 받아주세요!

**Comment by sosoYim** [comment]
저 pull 해도 들어오는게 없는데 뭐가 문제일까요..ㅠㅜ

**Comment by Hoya-kim** [comment]
> 저 pull 해도 들어오는게 없는데 뭐가 문제일까요..ㅠㅜ

강사님이 말씀하신대로 하면 되는데 혹시 잘 안되면 말씀주세요!

**Comment by sosoYim** [comment]
#6 풀리퀘스트 보내드렸습니다!

**Comment by Hoya-kim** [comment]
- 완료
